// Cloudflare Pages Function — emits /sw.js with the deploy's commit SHA
// embedded as the cache version. Every prod deploy gets a unique cache
// key automatically, so the activate-time old-cache purge always fires
// and no one has to remember to bump a version constant.
//
// Local dev (no CF_PAGES_COMMIT_SHA env) falls back to 'japanese-dev'.

function renderSW(version) {
  return `// Service worker for Japanese Learning Tools
// Auto-generated by functions/sw.js with CACHE = deploy commit SHA.
//
// Strategy:
//   - Precache only static non-HTML assets (icons, manifest, JSON data).
//   - Navigations + HTML: always network (passthrough) — CF Access can
//     issue auth redirects that we must not cache.
//   - /data/*.json: network-first with cache fallback.
//   - Other same-origin GETs (icons, JS, CSS): cache-first after first hit.
//   - /api/*: passthrough.
const CACHE = '${version}';
const PRECACHE = [
  '/manifest.webmanifest',
  '/icon-192.png',
  '/icon-512.png',
  '/apple-touch-icon.png',
  '/js/srs.js',
  '/js/gemini.js',
  '/js/quiz-card.js',
  '/js/sw-register.js',
  '/js/tts-cache.js',
  '/data/grammar-n5n4.json',
  '/data/kanji-n5n4.json',
  '/data/vocab-n5n4.json',
  '/data/phrases-tourist.json',
];

self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(CACHE)
      .then(c => c.addAll(PRECACHE))
      .then(() => self.skipWaiting())
      .catch(() => { /* precache is best-effort; don't block install */ })
  );
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', e => {
  const req = e.request;
  const url = new URL(req.url);

  if (req.mode === 'navigate') return;
  const accept = req.headers.get('accept') || '';
  if (accept.includes('text/html')) return;

  if (url.pathname.startsWith('/api/')) return;
  if (req.method !== 'GET' || url.origin !== location.origin) return;

  if (url.pathname.startsWith('/data/') && url.pathname.endsWith('.json')) {
    e.respondWith(
      fetch(req).then(resp => {
        if (resp && resp.ok && resp.type === 'basic') {
          const copy = resp.clone();
          caches.open(CACHE).then(c => c.put(req, copy));
        }
        return resp;
      }).catch(() => caches.match(req))
    );
    return;
  }

  e.respondWith(
    caches.match(req).then(hit =>
      hit || fetch(req).then(resp => {
        if (resp && resp.ok && resp.type === 'basic') {
          const copy = resp.clone();
          caches.open(CACHE).then(c => c.put(req, copy));
        }
        return resp;
      }).catch(() => hit)
    )
  );
});
`;
}

export async function onRequestGet({ env }) {
  const sha = (env.CF_PAGES_COMMIT_SHA || '').slice(0, 7);
  const version = sha ? `japanese-${sha}` : 'japanese-dev';
  return new Response(renderSW(version), {
    headers: {
      'Content-Type': 'application/javascript; charset=utf-8',
      // Revalidate SW script on every check so byte-level changes
      // (new commit SHA) are detected immediately by the browser.
      'Cache-Control': 'no-cache, must-revalidate',
      'Service-Worker-Allowed': '/',
    },
  });
}
